# Site settings
title: lboynton.com
description: "The personal website of Lee Boynton - web developer, software engineer, system administrator, front-end developer..."
baseurl: ""
url: "http://lboynton.com"
username:
    github: lboynton
    twitter: leeboynton
    linkedin: lboynton

# Build settings
markdown: kramdown
permalink: pretty
